version: "3.9"
services:

  scalyr:
    container_name: scalyr-docker-agent
    environment:
        - SCALYR_API_KEY=${SCALYR_API_KEY}
    volumes:
        - '/var/run/docker.sock:/var/scalyr/docker.sock'
        - '/var/lib/docker/containers:/var/lib/docker/containers'
    image: scalyr/scalyr-agent-docker-json

  cve-poc:
    build: cve-poc
    hostname: ldapsvr
    domainname: ldapsvr.test
    environment:
      - POC_ADDR=172.16.238.11
      - POC_PORT=80
      - LISTENER_ADDR=10.10.10.31
      - LISTENER_PORT=9001
    networks:
      cve-net:
        ipv4_address: 172.16.238.11
    depends_on:
      - "scalyr"
networks:
  cve-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

# ldap
# rmi
# dns
# nis
# nds
# corba
