version: "3.9"
services:

  scalyr:
    container_name: scalyr-docker-agent
    environment:
        - SCALYR_API_KEY=${SCALYR_API_KEY}
    volumes:
        - '/var/run/docker.sock:/var/scalyr/docker.sock'
        - '/var/lib/docker/containers:/var/lib/docker/containers'
    image: scalyr/scalyr-agent-docker-json

  cve-poc:
    build: cve-poc
    hostname: ldapsvr
    domainname: ldapsvr.test
    environment:
      - POC_ADDR=10.10.10.32
      - POC_PORT=80
      - LISTENER_ADDR=10.10.10.31
      - LISTENER_PORT=9001
    depends_on:
      - "scalyr"
    ports:
      - "1337:1337"    
# ldap
# rmi
# dns
# nis
# nds
# corba
