version: "3.9"
services:

  scalyr:
    container_name: scalyr-docker-agent
    environment:
        - SCALYR_API_KEY=${SCALYR_API_KEY}
    volumes:
        - '/var/run/docker.sock:/var/scalyr/docker.sock'
        - '/var/lib/docker/containers:/var/lib/docker/containers'
    image: scalyr/scalyr-agent-docker-json

  cve-web:
    build: cve-web
    hostname: websvr
    domainname: range.lab
    environment:
      - POC_USERNAME=user
      - POC_PASSWORD=1qaz2wsx
    ports:
      - "8080:8080"
    depends_on:
      - "scalyr"
  cve-neo:
    build: cve-neo
    hostname: neosvr
    domainname: range.lab
    environment:
      - TOMCAT_USERNAME=bob
      - TOMCAT_PASSWORD=3edc4rfv
    ports:
      - "8888:8080"
    depends_on:
      - "scalyr"

# ldap
# rmi
# dns
# nis
# nds
# corba
